import { getRequiredUserId } from "@/lib/access";
import { getJobs } from "@/lib/data";
import { JobActions } from "@/components/jobs/job-actions";

function budget(job: { budgetMin: number | null; budgetMax: number | null }) {
  if (!job.budgetMin && !job.budgetMax) return "Budget not specified";
  return `$${job.budgetMin?.toLocaleString() ?? "0"}-$${job.budgetMax?.toLocaleString() ?? "0"}`;
}

export default async function JobsPage() {
  const userId = await getRequiredUserId();
  const jobs = await getJobs(userId);
  return <main className="p-8"><div className="mb-6 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-semibold">Jobs</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Find the best-fit opportunities for your portfolio and skill set.</p></div><div className="rounded-md border border-slate-200 bg-white px-3 py-2 text-sm text-slate-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">{jobs.length} results</div></div><section className="grid gap-4 rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900 md:grid-cols-4">{[["Category", "All categories"], ["Budget", "Any"], ["Experience", "All levels"], ["Sort By", "Latest"]].map(([label, option]) => <div key={label}><label className="mb-2 block text-sm font-medium text-slate-600 dark:text-slate-300">{label}</label><select disabled className="w-full rounded-md border border-slate-200 bg-slate-50 p-2 dark:border-slate-700 dark:bg-slate-950"><option>{option}</option></select></div>)}</section><section className="mt-8 space-y-5">{jobs.length ? jobs.map((job) => { const match = job.analyses[0]?.matchScore; return <article key={job.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><h2 className="text-xl font-semibold">{job.title}</h2><div className="mt-2 flex flex-wrap gap-4 text-sm text-slate-600 dark:text-slate-300"><span>Client: {job.clientName ?? "Private client"}</span><span>Budget: {budget(job)}</span><span>Experience: {job.experienceLevel ?? "Flexible"}</span><span>{job.remote ? "Remote" : job.location ?? "On-site"}</span></div></div>{match ? <div className="rounded-lg bg-emerald-100 px-3 py-2 text-sm font-medium text-emerald-700 dark:bg-emerald-900 dark:text-emerald-200">Match: {match}%</div> : null}</div><div className="mt-4 flex flex-wrap gap-2">{job.skills.map((skill) => <span key={skill.id} className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-medium dark:border-slate-700 dark:bg-slate-950">{skill.name}</span>)}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm text-slate-600 dark:text-slate-300"><span>{job.postedAt ? `Posted ${job.postedAt.toLocaleDateString()}` : "Recently posted"}</span><JobActions jobId={job.id} saved={Boolean(job.savedJobs.length)} /></div></article>; }) : <div className="rounded-xl border border-dashed border-slate-300 p-10 text-center text-slate-500 dark:border-slate-700">No open jobs are available right now.</div>}</section></main>;
}
