import { AppShell } from "@/components/dashboard/app-shell";
import { getRequiredUserId } from "@/lib/access";
import { getAnalyticsData } from "@/lib/data";

export default async function AnalyticsPage() {
  const userId = await getRequiredUserId();
  const data = await getAnalyticsData(userId);
  const metrics = [["Applications sent", data.applications.toString()], ["Interviews", data.interviews.toString()], ["Average match score", data.averageMatch ? `${data.averageMatch}%` : "0"], ["Proposal success", `${data.proposalSuccess}%`]];
  const max = Math.max(...data.statusCounts.map((item) => item.count), 1);
  return <AppShell><div className="p-6 sm:p-8"><div className="mb-8"><h1 className="text-3xl font-semibold">Analytics</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Understand what is working across your freelance pipeline.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></div>)}</div><div className="mt-8 grid gap-6 xl:grid-cols-[1.4fr_0.6fr]"><section className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-semibold">Application pipeline</h2>{data.statusCounts.length ? <div className="mt-6 space-y-4">{data.statusCounts.map((item) => <div key={item.status}><div className="mb-1 flex justify-between text-sm"><span>{item.status}</span><span>{item.count}</span></div><div className="h-3 rounded-full bg-slate-200 dark:bg-slate-700"><div className="h-3 rounded-full bg-primary" style={{ width: `${(item.count / max) * 100}%` }} /></div></div>)}</div> : <p className="mt-6 text-sm text-slate-500">Not enough data yet. Your analytics will appear as you start applying to jobs.</p>}</section><section className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-semibold">Pipeline totals</h2><div className="mt-5 space-y-4 text-sm text-slate-600 dark:text-slate-300"><p>{data.applications} applications tracked</p><p>{data.interviews} interviews</p><p>{data.averageMatch ? `${data.averageMatch}% average job match` : "No analyzed jobs yet"}</p></div></section></div></div></AppShell>;
}
