import Link from "next/link";
import { AppShell } from "@/components/dashboard/app-shell";
import { getRequiredUserId } from "@/lib/access";
import { getDashboardData, getProfile } from "@/lib/data";

export default async function DashboardPage() {
  const userId = await getRequiredUserId();
  const [data, user] = await Promise.all([getDashboardData(userId), getProfile(userId)]);
  const stats = [["Jobs Analyzed", data.analyzed.toString(), "/analyze"], ["Saved Jobs", data.saved.toString(), "/saved"], ["Applications", data.applications.toString(), "/applications"], ["Interviews", data.interviews.toString(), "/applications"], ["Proposal Success Rate", data.applications ? `${Math.round((data.interviews / data.applications) * 100)}%` : "0%", "/analytics"]] as const;
  return <AppShell><div className="p-6 sm:p-8"><div className="mb-8"><h1 className="text-3xl font-semibold">Good morning, {user?.name ?? "freelancer"}</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Here&apos;s what&apos;s happening with your freelance pipeline.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{stats.map(([label, value, href]) => <Link href={href} key={label} className="rounded-xl border border-slate-200 bg-white p-4 shadow-soft hover:border-primary dark:border-slate-800 dark:bg-slate-900"><p className="text-sm text-slate-500">{label}</p><p className="mt-4 text-3xl font-semibold">{value}</p></Link>)}</div><div className="mt-8 grid gap-6 xl:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">Recent applications</h2><Link href="/applications" className="text-sm text-primary">View all</Link></div>{data.recentJobs.length ? <div className="space-y-4">{data.recentJobs.map(({ id, job, status }) => <Link href={`/applications/${id}`} key={id} className="flex items-center justify-between rounded-lg border border-slate-200 p-3 hover:border-primary dark:border-slate-700"><div><p className="font-medium">{job.title}</p><p className="text-sm text-slate-500">{status.toLowerCase()}</p></div><span className="text-sm font-medium">${job.budgetMax?.toLocaleString() ?? "-"}</span></Link>)}</div> : <p className="text-sm text-slate-500">No activity yet.</p>}</div><div className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Recommended jobs</h2><Link href="/jobs" className="text-sm text-primary">Browse jobs</Link></div>{data.recommendedJobs.length ? <div className="mt-4 space-y-4">{data.recommendedJobs.map((job) => <Link href={`/jobs/${job.id}`} key={job.id} className="flex items-center justify-between rounded-lg border border-slate-200 p-3 hover:border-primary dark:border-slate-700"><div><p className="font-medium">{job.title}</p><p className="text-sm text-slate-500">{job.category ?? "General"}</p></div><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-medium text-emerald-700 dark:bg-emerald-900 dark:text-emerald-200">{job.analyses[0]?.matchScore ?? "-"}%</span></Link>)}</div> : <p className="mt-4 text-sm text-slate-500">No recommendations yet.</p>}</div></div></div></AppShell>;
}
